### ISSUE TITLE
Dataset_link  is  out-of-date

### ISSUE THREAD

**Issue by chumingqian** [zhanghlgithub/smokeDetection#3]
> hi, 同学你好，数据集链接失效了，能否帮忙重新发一下链接呢 祝好，谢谢。

你可以在网络上 搜索中国科学院大学的 数据集， 很多是开源的

**Comment by baoxin1100** [comment]
hi,
同学你好，数据集链接失效了，能否帮忙重新发一下链接呢
祝好，谢谢。
